# Generated by Django 3.0.7 on 2020-12-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_delete_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Объявленная стоимость, грн.'),
        ),
        migrations.AddField(
            model_name='order',
            name='volume_general',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Общий объем, куб. м.'),
        ),
        migrations.AddField(
            model_name='order',
            name='weight',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Вес фактический, кг.'),
        ),
    ]
