# Generated by Django 3.0.7 on 2020-08-19 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('slug', models.SlugField(null=True)),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата заказа')),
                ('total_price', models.FloatField(blank=True, null=True, verbose_name='Сумма заказа')),
                ('customer_name', models.CharField(max_length=12, verbose_name='Имя и фамилия')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('delivery', models.CharField(blank=True, max_length=50, null=True, verbose_name='Способ доставки')),
                ('city', models.CharField(blank=True, max_length=20, null=True, verbose_name='Город')),
                ('post_office', models.CharField(blank=True, max_length=50, null=True, verbose_name='Почтовое отделение')),
                ('address', models.CharField(blank=True, max_length=20, null=True, verbose_name='Адрес доставки')),
                ('status', models.IntegerField(choices=[(1, 'Новый'), (2, 'В обработке'), (3, 'Выполнен')], default=1, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('new_price', models.IntegerField(blank=True, null=True, verbose_name='новая цена')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_image', to='app.Product', verbose_name='Название')),
            ],
            options={
                'verbose_name': 'изображение товара',
                'verbose_name_plural': 'изображения товара',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('quantity', models.FloatField(blank=True, null=True, verbose_name='Количество')),
                ('cost_product', models.FloatField(blank=True, null=True, verbose_name='Сумма')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='app.Order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Product')),
            ],
            options={
                'verbose_name': 'Контент заказа',
                'verbose_name_plural': 'Контент заказов',
            },
        ),
    ]
