# Generated by Django 3.0.7 on 2020-08-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='снять с продажи'),
        ),
    ]
