# Generated by Django 3.0.7 on 2020-06-29 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200628_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата заказа')),
                ('total_price', models.FloatField(blank=True, null=True, verbose_name='Сумма заказа')),
                ('customer_name', models.CharField(max_length=12, verbose_name='Имя')),
                ('customer_surname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('status', models.IntegerField(choices=[(1, 'Новый'), (2, 'В обработке'), (3, 'Выполнен')], default=1, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('quantity', models.FloatField(blank=True, null=True, verbose_name='Количество')),
                ('cost_product', models.FloatField(blank=True, null=True, verbose_name='Сумма')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='app.Order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Product')),
            ],
            options={
                'verbose_name': 'Контент заказа',
                'verbose_name_plural': 'Контент заказов',
            },
        ),
    ]
