# Generated by Django 3.0.7 on 2020-07-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='new_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='новая цена'),
        ),
    ]
