# Generated by Django 3.0.7 on 2020-07-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Способ доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='post_office',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Почтовое отделение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='new_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='новая цена'),
        ),
    ]
