# Generated by Django 3.0.7 on 2020-07-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200710_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_surname',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=12, verbose_name='Имя и фамилия'),
        ),
    ]
