# Generated by Django 3.0.7 on 2020-08-29 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200829_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.RemoveField(
            model_name='size',
            name='stock',
        ),
        migrations.CreateModel(
            name='ProductAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=10, null=True, verbose_name='Количество')),
                ('productName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Product', verbose_name='название модели')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Size', verbose_name='размер')),
            ],
            options={
                'verbose_name': 'наличие товара',
                'verbose_name_plural': 'наличие товаров',
            },
        ),
    ]
