# Generated by Django 3.0.7 on 2020-09-03 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200829_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productavailability',
            old_name='productName',
            new_name='product',
        ),
    ]
