# Generated by Django 3.0.7 on 2020-09-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200928_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='post_office',
            field=models.TextField(blank=True, null=True, verbose_name='Почтовое отделение'),
        ),
    ]
