# Generated by Django 3.0.7 on 2020-10-02 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_tableofsize'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tableofsize',
            options={'verbose_name': 'Название модели', 'verbose_name_plural': 'Названия модели'},
        ),
        migrations.AddField(
            model_name='product',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TableOfSize', verbose_name='таблица размеров'),
        ),
        migrations.AlterField(
            model_name='tableofsize',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
