# Generated by Django 3.0.7 on 2020-10-02 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20201002_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tableofsize',
            options={'verbose_name': 'Таблица размеров', 'verbose_name_plural': 'Таблицы размеров'},
        ),
        migrations.AlterField(
            model_name='product',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TableOfSize', verbose_name='таблица размеров'),
        ),
    ]
