# Generated by Django 3.0.7 on 2020-10-02 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20201002_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.TableOfSize', verbose_name='таблица размеров'),
        ),
    ]
