# Generated by Django 3.0.7 on 2020-10-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20201002_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productavailability',
            name='quantity',
            field=models.IntegerField(null=True, verbose_name='Количество'),
        ),
    ]
