# Generated by Django 3.0.7 on 2020-10-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20201010_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Способ оплаты'),
        ),
    ]
