# Generated by Django 3.0.7 on 2020-10-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20201024_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Доставка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Оплата'),
        ),
    ]
