# Generated by Django 3.0.7 on 2020-10-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20201024_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name="Номер накладной 'Новой почты'"),
        ),
    ]
