# Generated by Django 3.0.7 on 2020-10-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_order_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name="ТНН 'Новой почты'"),
        ),
    ]
