# Generated by Django 3.0.7 on 2020-10-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20201025_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='cost_product',
        ),
    ]
