# Generated by Django 3.0.7 on 2020-10-27 13:30

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_orderitem_cost_product'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='orderitem',
            managers=[
                ('cost_product', django.db.models.manager.Manager()),
            ],
        ),
    ]
