# Generated by Django 3.0.7 on 2020-10-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20201027_1630'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='orderitem',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cost_product',
            field=models.FloatField(blank=True, null=True, verbose_name='Сумма'),
        ),
    ]
