# Generated by Django 3.0.7 on 2020-10-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20201028_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quantity_breakpoint',
            field=models.FloatField(blank=True, null=True, verbose_name='Количество с сайта'),
        ),
    ]
