# Generated by Django 3.0.7 on 2020-11-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20201106_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Новый'), (2, 'В обработке'), (3, 'Выполнен'), (4, 'Отменен')], default=1, verbose_name='Статус'),
        ),
    ]
