# Generated by Django 3.0.7 on 2020-11-14 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20201114_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='pre_order',
            new_name='preorder',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pre_order',
            new_name='preorder',
        ),
    ]
