# Generated by Django 3.0.7 on 2020-11-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20201114_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='preorder',
        ),
        migrations.AddField(
            model_name='productavailability',
            name='preorder',
            field=models.BooleanField(default=False, verbose_name='Предзаказ'),
        ),
    ]
