# Generated by Django 3.0.7 on 2020-11-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_sale_salesummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата'),
        ),
    ]
