# Generated by Django 3.0.7 on 2020-11-17 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_sale_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='SaleSummary',
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
            ],
            options={
                'verbose_name': 'ТТН Новой почты',
                'verbose_name_plural': 'ТТН Новой почты',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.order',),
        ),
    ]
