# Generated by Django 3.0.7 on 2020-11-16 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_sale_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='SaleSummary',
        ),
    ]
