# Generated by Django 3.0.7 on 2020-11-24 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20201117_2014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
