# Generated by Django 3.0.7 on 2020-12-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20201202_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city_ref',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Код города'),
        ),
        migrations.AddField(
            model_name='order',
            name='date_send',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки'),
        ),
        migrations.AddField(
            model_name='order',
            name='post_office_ref',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Номер отделения'),
        ),
    ]
