# Generated by Django 3.0.7 on 2020-12-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20201203_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_send',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отправки'),
        ),
    ]
