# Generated by Django 3.0.7 on 2020-12-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_order_cost_on_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='volume_general',
        ),
        migrations.RemoveField(
            model_name='order',
            name='weight',
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
