# Generated by Django 3.0.7 on 2021-01-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20201209_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключ текста')),
                ('value', models.TextField(blank=True, null=True, verbose_name='Значение на русском')),
                ('value_ua', models.TextField(blank=True, null=True, verbose_name='Значение на украинском')),
            ],
        ),
    ]
