# Generated by Django 3.0.7 on 2021-01-11 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_localization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localization',
            options={'verbose_name': 'Локализация', 'verbose_name_plural': 'Локализации'},
        ),
    ]
