# Generated by Django 3.0.7 on 2021-01-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_auto_20210111_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='localization',
            name='value_en',
            field=models.TextField(blank=True, null=True, verbose_name='Значение на английском'),
        ),
    ]
