# Generated by Django 3.0.7 on 2021-01-19 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_localization_value_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_locale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='description_translate', to='app.Localization', verbose_name='перевод описания'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_locale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title_translate', to='app.Localization', verbose_name='перевод названия'),
        ),
    ]
