# Generated by Django 3.0.7 on 2021-01-19 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_auto_20210119_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_locale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='description_translate', to='app.Localization', verbose_name='перевод описания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_locale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title_translate', to='app.Localization', verbose_name='перевод названия'),
        ),
    ]
