# Generated by Django 3.0.7 on 2021-01-24 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_auto_20210119_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localization',
            name='value_en',
        ),
    ]
