# Generated by Django 3.0.7 on 2021-11-27 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_auto_20211127_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название перевода')),
                ('name_locale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Localization', verbose_name='перевод')),
            ],
        ),
    ]
