# Generated by Django 3.0.7 on 2021-11-29 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_translates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translates',
            options={'verbose_name': 'Перевод', 'verbose_name_plural': 'Переводы'},
        ),
        migrations.AlterField(
            model_name='translates',
            name='name_locale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Localization', verbose_name='ключ для перевода'),
        ),
    ]
