# Generated by Django 3.0.7 on 2021-12-16 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_product_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_description',
        ),
        migrations.AddField(
            model_name='category',
            name='category_description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_description_translate', to='app.Localization', verbose_name='описание категории'),
        ),
    ]
