# Generated by Django 3.0.7 on 2022-09-30 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_category_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Translates',
        ),
    ]
